### ISSUE TITLE
Show package on "Select version" step

### ISSUE THREAD

**Issue by gpbmike** [dance2die/bunpkg-client#6]
It would be nice to see the package you chose in the "Select version" step.

I think I somehow selected the wrong package (perhaps race condition) while searching. I only noticed because the version numbers weren't what I was expecting. You would probably see the mistake "links" step but it was a little jarring.

![image](https://user-images.githubusercontent.com/8754/50606511-e1497f00-0e7a-11e9-9ef9-e20e0d232650.png)

**Comment by gpbmike** [comment]
Cool tool by the way.

**Comment by dance2die** [comment]
Thanks @gpbmike. 
That does looks troublesome as one can get links for wrong package.
I will work on it~

**Comment by dance2die** [comment]
@gpbmike I've added the package name above the `stable versions only` checkbox after a few layouts below and above it because I wanted the package name to stand out, and below the checkbox it looked weird 😉

It's live now~ 🎊😃

![2019-01-02_16-06-58](https://user-images.githubusercontent.com/8465237/50612613-8c246200-0ea8-11e9-83b9-90e15254d8e5.gif)
